version: "3.9"

x-base: &base
  image: family_website
  env_file: .env
  volumes:
    - .:/app
  labels:
    me.zmudzinski: family-website

services:
  web:
    <<: *base
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    command: runserver
    ports:
      - "8000:8000"
